### ISSUE TITLE
run Loadbalance.py 

### ISSUE THREAD

**Issue by parkinseo** [nayanseth/sdn-floodlight-loadbalancing#21]
Traceback (most recent call last):
File "LoadBalance.py", line 332, in <module>
loadbalance()
File "LoadBalance.py", line 265, in loadbalance
getLinkCost()
File "LoadBalance.py", line 147, in getLinkCost
getResponse(stats,"linkTX")
File "LoadBalance.py", line 26, in getResponse
response.raise_for_status()
File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

the bug when I run loadbalance.py
Help me fix it.
Thank you

**Comment by nayanseth** [comment]
Please raise a pull request

**Comment by madurak25** [comment]
I am having the same issue can you help fix it?

**Comment by aish6595** [comment]
Hi I am facing the same problem. How can I fix it?
